### ISSUE TITLE
Getting error during build process

### ISSUE THREAD

**Issue by GeorvityLabs** [acids-ircam/rave_vst#2]
```
[100%] Linking CXX shared module rave-vst_artefacts/Release/VST3/RAVE.vst3/Contents/x86_64-linux/RAVE.so
/usr/bin/ld: /tmp/RAVE.Nl6RwU.ltrans6.ltrans.o: in function `juce::MidiOutput::run()':
<artificial>:(.text+0x782b): undefined reference to `snd_midi_event_encode'
/usr/bin/ld: <artificial>:(.text+0x7860): undefined reference to `snd_seq_event_output_direct'
/usr/bin/ld: <artificial>:(.text+0x7877): undefined reference to `snd_midi_event_reset_encode'
/usr/bin/ld: <artificial>:(.text+0x79eb): undefined reference to `snd_midi_event_free'
/usr/bin/ld: <artificial>:(.text+0x79fa): undefined reference to `snd_midi_event_new'
/usr/bin/ld: /tmp/RAVE.Nl6RwU.ltrans6.ltrans.o: in function `std::default_delete<juce::(anonymous namespace)::ALSADevice>::operator()(juce::(anonymous namespace)::ALSADevice*) const [clone .isra.0] [clone .part.0] [clone .lto_priv.0]':
.
.
.
.
<artificial>:(.text+0x3eea): undefined reference to `snd_midi_event_encode'
/usr/bin/ld: <artificial>:(.text+0x3f25): undefined reference to `snd_seq_event_output_direct'
/usr/bin/ld: <artificial>:(.text+0x3f3c): undefined reference to `snd_midi_event_reset_encode'
/usr/bin/ld: <artificial>:(.text+0x442b): undefined reference to `snd_midi_event_free'
/usr/bin/ld: <artificial>:(.text+0x443a): undefined reference to `snd_midi_event_new'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/rave-vst_Standalone.dir/build.make:225: rave-vst_artefacts/Release/Standalone/RAVE] Error 1
make[1]: *** [CMakeFiles/Makefile2:237: CMakeFiles/rave-vst_Standalone.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target rave-vst_VST3
make: *** [Makefile:130: all] Error 2
```

Any ideas on how to fix this?

**Comment by caillonantoine** [comment]
On what OS are you building the project ?

**Comment by ZodiacFRA** [comment]
Could you use the triple ticks to format your text as a code block please?
I think what you're missing is the alsa lib (alsa-lib-devel if you're using dnf)

**Comment by GeorvityLabs** [comment]
Ubuntu 20.04 LTS

**Comment by GeorvityLabs** [comment]
> alsa-lib-devel

Any way I can fix this with an apt install?
what would be the package name.
Because , i did install libasound2-dev

**Comment by ZodiacFRA** [comment]
Could you post the output you got with ``` cmake .. -DCMAKE_BUILD_TYPE=Release``` ?

**Comment by taucontrib** [comment]
> > alsa-lib-devel
> 
> Any way I can fix this with an apt install? what would be the package name. Because , i did install libasound2-dev

Installing the packages 
_libwebkit2gtk-4.0-dev_ _libcurl4-gnutls-dev_ _libasound2-dev_ 
as well as renaming the folder `/rave_vst/JUCE` into `/rave_vst/juce` solved my issue during the build on Ubuntu 20.04 LTS

**Comment by ZodiacFRA** [comment]
Thanks for the feedback :) I'll update the readme with those dependencies
